### ISSUE TITLE
fast scrolling idea, elliminate the need for separate position control

### ISSUE THREAD

**Issue by webgress** [asvd/intence#2]
Read your article on habrahabr.
Love your design.
Lots of critics with 2 main (valid) concernes : position indication, fast-direct scrolling.
Don't see a way to solve position indication ...
But here is a way for fast direct scrolling that would make sense with your design.
I think it would feel natural if a user could drag/stretch the indicator from bottom up to scroll down, where if the mouse reaches the top of the scrollable area that would correspond to scrolling 100% down.
Your indicator does look a bit like a scroll (in a sence of "ancient scrolls") so the draggin action may feel natural as if unrolling more of the paper from the bootom roll (or from the top when if draggin from the top indicator).

Another unrelated visual idea/question : could the textrue be made to look like a crumpled paper where scrolling action would sort of crush it in one direction and straighten from the other ?

**Comment by asvd** [comment]
Thx for the feedback. I have the following vision currently (let me know if you think I am wrong on something):
- On "paper" indication: what happens to the texture mostly depends on some maths beyond the indicator. There's not to much image types suitable for the indicator, the only way to figure out if it works is to try it. Let me know if you have some intersting representation with a paper-like texture.
- For scrolling with mouse drag: There is no clear border between where the indicator ends and the content begins - therefore there is no reason why dragging with the mouse should only work for the indicator, but not for the content as a whole. For scrolling with mouse drag there is a dragscroll library: https://github.com/asvd/dragscroll.
- Concerning the issue of quickly scrolling to the beginning / end of the content: this is not always necessary and depends on the type of content. Therefore it should be implemented when necessary by other solutions like https://github.com/asvd/viewport
- On position indication: this is also subject for the viewport.js, because it depends on the content what exactly should be displayed in order to demonstrate user where he is.
